// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP47c6fVuMID9wH-DLbX4lRRZR6IhsO6w',
    appId: '1:120525223197:web:cfb72ff07973bc48c31df4',
    messagingSenderId: '120525223197',
    projectId: 'frisky-fruits',
    authDomain: 'frisky-fruits.firebaseapp.com',
    storageBucket: 'frisky-fruits.firebasestorage.app',
    measurementId: 'G-YS46378L8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5U3Q1Q47uBKbhhmKYmxydLhyrcwO1Do',
    appId: '1:120525223197:android:b6342723eef6b850c31df4',
    messagingSenderId: '120525223197',
    projectId: 'frisky-fruits',
    storageBucket: 'frisky-fruits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkvMEIr6_KVDtsKRH99iRe2ABjFdtNmIo',
    appId: '1:120525223197:ios:a716cb08ae36d7cfc31df4',
    messagingSenderId: '120525223197',
    projectId: 'frisky-fruits',
    storageBucket: 'frisky-fruits.firebasestorage.app',
    iosBundleId: 'com.example.friskyFruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkvMEIr6_KVDtsKRH99iRe2ABjFdtNmIo',
    appId: '1:120525223197:ios:a716cb08ae36d7cfc31df4',
    messagingSenderId: '120525223197',
    projectId: 'frisky-fruits',
    storageBucket: 'frisky-fruits.firebasestorage.app',
    iosBundleId: 'com.example.friskyFruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP47c6fVuMID9wH-DLbX4lRRZR6IhsO6w',
    appId: '1:120525223197:web:0070b2f2d2517c03c31df4',
    messagingSenderId: '120525223197',
    projectId: 'frisky-fruits',
    authDomain: 'frisky-fruits.firebaseapp.com',
    storageBucket: 'frisky-fruits.firebasestorage.app',
    measurementId: 'G-X9934Y7W9X',
  );
}
